Repository saeloun/miru-docs, pull requests merged in 2022-10, with the labels that each got.

#5 Setup url updated in guidelines
  docs/contributing-guide/guidelines.md
Labels: PR: unreviewed

#7 Miru Docs color theme updated
  src/css/custom.css
Labels: hacktoberfest-approved, PR: unreviewed

#8 Update intro.md
  docs/intro.md
Labels: PR: unreviewed

#11 add docker setup guide to contribution guides
  docs/contributing-guide/setup/docker.md
Labels: PR: reviewed-approved

#13 Getmiru.com to miru.so
  README.md
  docusaurus.config.js
Labels: PR: unreviewed

#14 Update logo and respective link from getmiru.com to miru.so
  docusaurus.config.js
Labels: PR: reviewed-approved
